name: Reusable Birdbot Deploy

on:
  workflow_call:

jobs:
  deploy-prod:
    runs-on: self-hosted
    steps:

      - name: Configure GH
        env:
          PAT: ${{ secrets.PAT }}
          REPOSITORY: ${{ github.repository }}
        run: |
          git config remote.origin.url 'https://$PAT@github.com/$REPOSITORY'
          working-directory: /opt/kurzgesagt/kurzgesagt_bot_refactor

      - name: Pull Updated Code
        run: |  
          git pull origin public-refactor
          working-directory: /opt/kurzgesagt/kurzgesagt_bot_refactor
          
      - name: Restart Service
        run: |
          systemctl restart birdbot.service
