name: Reusable Birdbot Deploy

on:
  workflow_call:

jobs:
  deploy-prod:
    if: ${{ github.ref_name == 'master' }}
    runs-on: self-hosted
    steps:

      - name: Pull Updated Code
        run: |  
          git pull origin master
        working-directory: /opt/kurzgesagt/kurzgesagt_bot

      - name: Update Deps
        run: |
          pip install -r requirements.txt
          
      - name: Restart Service
        run: |
          sudo systemctl restart birdbot.service
          
  deploy-staging:
    if: ${{ github.ref_name == 'staging' || 'public-refactor' || 'staging-deploy'}}
    runs-on: self-hosted
    steps:

      - name: Pull Updated Code
        run: |  
          git pull origin public-refactor
        working-directory: /opt/kurzgesagt/kurzgesagt_bot_refactor

      - name: Update Deps
        run: |
          pip install -r requirements.txt
          
      - name: Restart Service
        run: |
          sudo systemctl restart birdbot-test.service
