name: Reusable Birdbot Deploy

on:
  workflow_call:

jobs:
  deploy-prod:
    runs-on: self-hosted
    steps:
      - name: Pull Updated Code
        run: |
          cd /opt/kurzgesagt/kurzgesagt_bot_refactor && git pull origin public-refactor

      - name: Restart Service
        run: |
          systemctl restart birdbot.service
