name: Reusable License Checker

on: 
  workflow_call:
  
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Checkout repo with license config
        uses: actions/checkout@v4
        with:
          repository: kurzgesagt-in-a-nutshell/.github
          path: license-config
          ref: license
        
      - name: Check license headers
        uses: viperproject/check-license-header@v2
        with:
          path: ./
          config: ./license-config/.github/license-headers/license-check-config.json
          strict: false
