name: Reusable License Checker

on: 
  workflow_call:
  
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: checkout
        uses: actions/checkout@v3

      - name: Check license headers
        uses: viperproject/check-license-header@v2
        with:
          path: ./
          config: ./.github/license-headers/license-check-config.json
          strict: false
