name: Reusable License Checker

on: 
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
  
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Check license headers
        uses: viperproject/check-license-header@v2
        with:
          path: .
          config: ${{ inputs.config_path }}
          strict: false
